# Generated by Django 5.2 on 2025-06-19 20:06

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('show_on_homepage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('background_image', models.ImageField(upload_to='home/')),
                ('button_text', models.CharField(max_length=50)),
                ('button_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('about', 'About Section'), ('services', 'Services Section'), ('features', 'Features Section'), ('team', 'Team Section'), ('contact', 'Contact Section')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('background_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('show_section', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='Use Font Awesome or Bootstrap Icons class names', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('color', colorfield.fields.ColorField(default='#4e73df', image_field=None, max_length=25, samples=None)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='site/')),
                ('favicon', models.ImageField(upload_to='site/')),
                ('primary_color', colorfield.fields.ColorField(default='#4e73df', image_field=None, max_length=25, samples=None)),
                ('secondary_color', colorfield.fields.ColorField(default='#1cc88a', image_field=None, max_length=25, samples=None)),
                ('dark_color', colorfield.fields.ColorField(default='#5a5c69', image_field=None, max_length=25, samples=None)),
                ('light_color', colorfield.fields.ColorField(default='#f8f9fc', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('client_image', models.ImageField(upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
