# Generated by Django 5.2 on 2025-06-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_career_news_project_alter_pagesection_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='clients/')),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('testimonial', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('video_url', models.URLField(blank=True, help_text='URL to YouTube or other video platform', null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Media Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_name',
            field=models.CharField(choices=[('about', 'About Section'), ('services', 'Services Section'), ('projects', 'Projects Section'), ('news', 'News Section'), ('career', 'Career Section'), ('contact', 'Contact Section'), ('team', 'Team Section'), ('media', 'Media Section'), ('partners', 'Partners Section'), ('clients', 'Clients Section')], max_length=50, unique=True),
        ),
    ]
