# Generated by Django 5.2.4 on 2025-07-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_client_mediaitem_partner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField()),
                ('summary', models.TextField(help_text='Short summary of your qualifications')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='website.career')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
